CREATE TABLE TEMPORARY1
(
COMPANY VARCHAR2(100) PRIMARY KEY,
SECTOR VARCHAR2(50),
INDUSTRY VARCHAR2(50),
MARKETCAP INT,
PRICE INT,
PE INT,
EBITDA INT);

SELECT * FROM TEMPORARY1;










SELECT * FROM BSEIT;
SELECT * FROM(
SELECT COMPANY,SECTOR,INDUSTRY,ROUND(MARKET_CAP,0) MARKETCAP,ROUND(PRICE,0) PRICE,ROUND((PRICE/EARNING_PER_SHARE),0) PE,ROUND((ENTERPRISE_VALUE/EVEBITDA),0) EBITDA FROM BSEIT1)
WHERE PE >=0;