
CREATE TABLE CHECKTABLE_TRGT
(
ID NUMBER,
NAME VARCHAR2(20),
MARKS NUMBER
);

select * from CHECKTABLE_TRGT;
---CHECK COUNT
SELECT COUNT(*) FROM CHECKTABLE_TRGT;---COUNT-4.

---CHECK DUPLICATE.
SELECT ID, NAME, MARKS, COUNT(*) FROM CHECKTABLE_TRGT
GROUP BY ID, NAME, MARKS
HAVING COUNT(*)>1;

---CHECK SOURCE DATA PRESENT IN SOURCE AND NOT PRESENT IN TARGWT.
SELECT * FROM source.CHECKTABLE
MINUS
SELECT * FROM target.CHECKTABLE_TRGT;

---CHECKING TARGET DATA PRESENT IN TARGET AND NOT PRESENT IN SOURCE
SELECT * FROM target.CHECKTABLE_TRGT
MINUS
SELECT * FROM source.CHECKTABLE;