SELECT * FROM (
SELECT ROWNUM R, E.* FROM HR.EMPLOYEES E)
WHERE MOD(R,2)=0; 

SELECT * FROM (
            SELECT ROWNUM R , E.* FROM EMPLOYEES E)
WHERE MOD(R,2)<>0;

SELECT E.* FROM EMPLOYEES E
WHERE MOD(EMPLOYEE_ID,2) = 0;

SELECT E.* FROM EMPLOYEES E
WHERE MOD(EMPLOYEE_ID,2) <> 0;


SELECT * FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'DAY') LIKE '%MONDAY%';

SELECT EMPLOYEE_ID,COUNT(*) FROM EMPLOYEES
GROUP BY EMPLOYEE_ID HAVING COUNT(*)>2;

SELECT * FROM (      
        SELECT E.*,COUNT(*) OVER(PARTITION BY EMPLOYEE_ID)  R FROM EMPLOYEES E) 
WHERE R>2;


SELECT * FROM (
SELECT ROWNUM R ,E.* FROM EMPLOYEES E)
WHERE R <=10;


SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.EMAIL, E.PHONE_NUMBER, E.HIRE_DATE, F.JOB_ID, F.SALARY, F.COMMISSION_PCT, F.MANAGER_ID, F.DEPARTMENT_ID FROM EMPLOYEES E
INNER JOIN EMPLOYEES F
ON E.EMPLOYEE_ID = F.MANAGER_ID
ORDER BY F.MANAGER_ID;


SELECT EMPLOYEE_ID,DEPARTMENT_ID, FIRST_NAME,ABS((TO_CHAR(HIRE_DATE,'YYYY')-TO_CHAR(SYSDATE,'YYYY')))  "YEAR OF EXPERIANCE" FROM EMPLOYEES 
WHERE ABS((TO_CHAR(HIRE_DATE,'YYYY')-TO_CHAR(SYSDATE,'YYYY'))) > 5 AND FIRST_NAME LIKE 'L%';

WITH DS AS( SELECT (FIRST_NAME||' '||LAST_NAME) D FROM EMPLOYEES)
    SELECT SUBSTR(D,1,INSTR(D,' ',1,1)-1) FIRST_NAME, SUBSTR(D,INSTR(D,' ',1,1)+1) LAST_NAME FROM DS;
    
SELECT * FROM (  
                SELECT E.*, DENSE_RANK() OVER(ORDER BY SALARY DESC) R FROM EMPLOYEES E) 
WHERE R=2;

SELECT MAX(SALARY) FROM EMPLOYEES WHERE SALARY <(SELECT MAX(SALARY) FROM EMPLOYEES
WHERE SALARY <(SELECT MAX(SALARY) FROM EMPLOYEES));

    
SELECT E.FIRST_NAME,D.department_name FROM employees E
INNER JOIN departments D
ON E.department_id=D.department_id
WHERE SALARY IN (SELECT MAX(SALARY) FROM EMPLOYEES);
    
   
SELECT * FROM EMPLOYEES
WHERE ROWNUM<=8
MINUS
SELECT * FROM EMPLOYEES
WHERE ROWNUM<=4;


SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID >=104 AND EMPLOYEE_ID<=107;


SELECT LEVEL FROM DUAL
CONNECT BY LEVEL <=10;

WITH DS AS(SELECT 'RAJU' D FROM DUAL)
SELECT SUBSTR(D,LEVEL,1) FROM DS
CONNECT BY LEVEL <=LENGTH(D);



WITH DS AS(SELECT 'RAJKUMARRAO' D FROM DUAL)
SELECT SUBSTR(D,LEVEL,LEVEL) FROM DS
CONNECT BY LEVEL <=LENGTH(D);

SELECT * FROM (
SELECT E.*,DENSE_RANK() OVER(ORDER BY salary DESC) H,DENSE_RANK() OVER(ORDER BY salary ASC) L FROM EMPLOYEES E)
WHERE H=1 OR L=1;


SELECT * FROM EMPLOYEES
WHERE SUBSTR(FIRST_NAME,1,1)='M';

SELECT * FROM EMPLOYEES
WHERE SUBSTR(FIRST_NAME,-1,1)='s';

SELECT * FROM EMPLOYEES
WHERE SUBSTR(FIRST_NAME,1,1) IN ('A','E','I','O','U');

SELECT * FROM EMPLOYEES
WHERE SUBSTR(FIRST_NAME,-1,1) IN ('a','e','i','o','U');

SELECT * FROM EMPLOYEES
WHERE SUBSTR(FIRST_NAME,2,1) IN ('a','e','i','o','u');



