SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID IN (            
                    SELECT MANAGER_ID FROM EMPLOYEES);

SELECT * FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'YYYY')<=2002;

SELECT SALARY, ROUND(SALARY/30) DAILY_SAL, SALARY*12 ANNUAL_SAL FROM EMPLOYEES
ORDER BY SALARY*12 ASC;

SELECT EMPLOYEE_ID, FIRST_NAME,HIRE_DATE, JOB_ID,ROUND((SYSDATE- HIRE_DATE)/365) EXP FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (SELECT DISTINCT MANAGER_ID FROM EMPLOYEES);

SELECT EMPLOYEE_ID, FIRST_NAME,HIRE_DATE, JOB_ID,ROUND((SYSDATE- HIRE_DATE)/365) EXP FROM EMPLOYEES
WHERE MANAGER_ID=100;

---List the emps in the asc order of Designations of those joined after the second half of 2005.
SELECT * FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'YYYY')= 2005 AND TO_CHAR(HIRE_DATE,'MM')> 6
ORDER BY JOB_ID ASC;

---List the emps along with their Exp and Daily Sal is more than Rs.100
SELECT E.*, ROUND((SALARY*12)/365) DAILY_SAL , ROUND(MONTHS_BETWEEN(SYSDATE,hire_date)/12) EXP  FROM EMPLOYEES E
WHERE ROUND((SALARY*12)/365)>100;

---List the emps who are either ‘CLERK’ or ‘ANALYST’ in the Desc order
SELECT * FROM EMPLOYEES
WHERE JOB_ID = 'SH_CLERK' OR JOB_ID = 'FI_ACCOUNT'
ORDER BY JOB_ID DESC;

----List the emps who joined on 1-MAY-81,3-DEC-81,17-DEC-81,19-JAN-80 in asc order of seniority.
SELECT * FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'DD-MM-YYYY') IN ('13-01-2001','16-08-2002','07-12-2002');

----List the emp who are working for the Deptno 10 or20
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (10,20);

---List the emps who are joined in the month of Aug 1980
SELECT * FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'YYYY')=2005 AND TO_CHAR(HIRE_DATE,'MON')='AUG';

---. List the Enames those are having five characters in their Names.
SELECT FIRST_NAME FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_____';

SELECT FIRST_NAME FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) =5;

----List the Enames those are starting with ‘S’ and with five characters
SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'S%' AND LENGTH(FIRST_NAME)=5;










