create database sql101;

CREATE TABLE CUSTOMER
(
CUST_ID INT IDENTITY NOT NULL,
FIRST_NAME NVARCHAR(50) NULL,
LAST_NAME NVARCHAR(50) NULL,
BIRTHDATE DATE NULL,
GENDER NCHAR(1) NULL,
);

ALTER TABLE CUSTOMER
ADD MARITALSTATUS NCHAR(1) NULL;

ALTER TABLE CUSTOMER
ALTER COLUMN FIRST_NAME NVARCHAR(100) NULL;

ALTER TABLE CUSTOMER
ALTER COLUMN LAST_NAME NVARCHAR(100);

ALTER TABLE CUSTOMER
DROP COLUMN GENDER;


DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER
(
CUSTOMER_ID INT IDENTITY NOT NULL,
FIRST_NAME NVARCHAR(50) NULL,
LAST_NAME NVARCHAR(50) NULL,
GENDER NCHAR(1),
BIRTHDATE DATE NULL,
);

ALTER TABLE CUSTOMER
ALTER COLUMN FIRST_NAME NVARCHAR(60);

ALTER TABLE CUSTOMER
ALTER COLUMN GENDER NCHAR(2);

ALTER TABLE CUSTOMER
ALTER COLUMN GENDER NCHAR(1);

ALTER TABLE CUSTOMER
DROP COLUMN GENDER;

ALTER TABLE CUSTOMER
ADD GENDER NCHAR(1) NULL;

ALTER TABLE CUSTOMER
DROP COLUMN GENDER;

CREATE TABLE CHETHAN
(
CUST_ID INT IDENTITY NOT NULL,
SALARY NCHAR(6) NULL,
DEPARTMENT_ID INT NOT NULL,
);

ALTER TABLE CHETHAN
ADD DEPARTMENT_ID NCHAR(6) NULL;

ALTER TABLE CHETHAN
ALTER COLUMN  DEPARTMENT_ID INT NOT NULL;

ALTER TABLE CHETHAN 
ADD GENDER NCHAR(1) NULL;

ALTER TABLE CHETHAN
DROP COLUMN GENDER;

DROP TABLE CHETHAN;

